spring.application.name=backend

server.port=8080

spring.datasource.url= jdbc:mysql://localhost:3306/smartParkHub?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
app.jwt.secret=SmartParkHubSecretKey2026!XyZ#QwErTy@Campus@Parking@System@SecureKey
app.jwt.expiration-ms=86400000
